# Generated by Django 4.0.6 on 2022-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('KH', 'KING-HOTEL'), ('FSH', 'FIVE-STAR-HOTEL'), ('LH', 'LUXE-HOTEL'), ('DH', 'DELUXE-HOTEL')], max_length=20),
        ),
    ]
