# Generated by Django 4.0.6 on 2022-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('DH', 'DELUXE-HOTEL'), ('KH', 'KING-HOTEL'), ('LH', 'LUXE-HOTEL'), ('FSH', 'FIVE-STAR-HOTEL')], max_length=20),
        ),
    ]
